### ISSUE TITLE
Statusbar and splash screen

### ISSUE THREAD

**Issue by arthurflor23** [jeneser/ionic-super-bar#11]
Hi!
Well, I got it the status bar transparent following your tips, but when app start in the splash screen, the status bar is always black. =/
Any ideia?

**Comment by jeneser** [comment]
Thanks for opening an issue with me.
I noticed the problem. I'm trying different solutions. But, i don't have a good solution for the moment.If you find the solution, I'm happy to accept a pull request.

**Comment by arthurflor** [comment]
I have no solution either :/

**Comment by Sampath-Lokuge** [comment]
@arthurflor Just hide the `status bar` when splash screen moment.

**Comment by luiferjf** [comment]
any solution for this?

**Comment by jeneser** [comment]
Not yet. There is no good solution now. :disappointed: 
You can try this method:
> @arthurflor Just hide the status bar when splash screen moment.

**Comment by GitMr** [comment]
in org.apache.cordova/splashscreen/SplashScreen.java:
//splashDialog = new Dialog(context, android.R.style.Theme_Translucent_NoTitleBar);（old）
splashDialog = new Dialog(context, android.R.style.Theme_Black_NoTitleBar_Fullscreen); （new）
