### ISSUE TITLE
Upgrade to Ionic 3

### ISSUE THREAD

**Issue by Sampath-Lokuge** [jeneser/ionic-super-bar#12]
Hi,
Can you please upgrade this project to Ionic 3? Thanks.

**Comment by jeneser** [comment]
Yes, I'll be happy to upgrade this project to Ionic 3. I just need a little time...
Thank you so much.

**Comment by Sampath-Lokuge** [comment]
It seems you have done the upgrade no? Hope you'll change the Readme file too.Thanks 👍

**Comment by jeneser** [comment]
Right, I have finished it. Supper is ready...😋
After, I'll close this issue.
Thank you so much.

**Comment by Sampath-Lokuge** [comment]
Not yet.You have to change this too with latest CLI `ionic cordova platform add android`  :D

**Comment by jeneser** [comment]
Yep, you are right. I have updated it. It should be ok now?

**Comment by Sampath-Lokuge** [comment]
Yep, Great!
